declare module '*.scss';

declare global {
  interface Window {
    Five9SocialWidget: unknown;
    REACT_APP_API_APPLICATION_NAME: string;
    REACT_APP_API_DEMO_APPLICATION_NAME: string;
    REACT_APP_API_URL: string;
    REACT_APP_CONFIG_DOMAIN: string;
    REACT_APP_OKTA_ISSUER_PATH: string;
    REACT_APP_SESSION_TIMEOUT_IN_MINUTES: string;
    REACT_APP_SESSION_WARNING_IN_MINUTES: string;
    REACT_APP_STANDARD_PORTAL_APPLICATION_NAME: string;
    REACT_APP_STANDARD_PORTAL_USERNAME: string;
    REACT_APP_STANDARD_PORTAL_PASSWORD: string;
    REACT_APP_REGENERON_PORTAL_USERNAME: string;
    REACT_APP_REGENERON_PORTAL_PASSWORD: string;
    REACT_APP_PHYZ_PORTAL_USERNAME: string;
    REACT_APP_PHYZ_PORTAL_PASSWORD: string;
    REACT_APP_VERRICA_PORTAL_USERNAME: string;
    REACT_APP_VERRICA_PORTAL_PASSWORD: string;
    REACT_APP_SERVICES_GATEWAY_URL: string;
    REACT_APP_GOOGLE_MAP_API_KEY: string;
  }
}

window.Five9SocialWidget = window.Five9SocialWidget || {};
window.REACT_APP_API_APPLICATION_NAME = window.REACT_APP_API_APPLICATION_NAME || '';
window.REACT_APP_API_DEMO_APPLICATION_NAME = window.REACT_APP_API_DEMO_APPLICATION_NAME || '';
window.REACT_APP_API_URL = window.REACT_APP_API_URL || '';
window.REACT_APP_CONFIG_DOMAIN = window.REACT_APP_CONFIG_DOMAIN || '';
window.REACT_APP_FIVE9_PROFILE = window.REACT_APP_FIVE9_PROFILE || '';
window.REACT_APP_OKTA_ISSUER_PATH = window.REACT_APP_OKTA_ISSUER_PATH || '';
window.REACT_APP_SESSION_TIMEOUT_IN_MINUTES = window.REACT_APP_SESSION_TIMEOUT_IN_MINUTES || '';
window.REACT_APP_SESSION_WARNING_IN_MINUTES = window.REACT_APP_SESSION_WARNING_IN_MINUTES || '';
window.REACT_APP_STANDARD_PORTAL_APPLICATION_NAME = window.REACT_APP_STANDARD_PORTAL_APPLICATION_NAME || '';
window.REACT_APP_STANDARD_PORTAL_USERNAME = window.REACT_APP_STANDARD_PORTAL_USERNAME || '';
window.REACT_APP_STANDARD_PORTAL_PASSWORD = window.REACT_APP_STANDARD_PORTAL_PASSWORD || '';
